package es.unican.istr.rtgen.system.elements.config;

import java.util.ArrayList;

/**
 * Created by JuanCTR on 01/09/2015.
 */
public enum LinearSystemConfigurableOptions {
    SEED, N_PROCESSORS, N_FLOWS, N_TASKS, RANDOM_LENGTH, SINGLE_FLOWS, SCHED_POLICY,
    PERIOD_DISTRIBUTION, PERIOD_BASE, PERIOD_RATIO,
    DEADLINE, TASK_LOCALIZATION,
    UTILIZATION_START, UTILIZATION_STEP, UTILIZATION_TOP, UTILIZATION_BCET_FACTOR, UTILIZATION_WCET_METHOD, UTILIZATION_BALANCING
}
