package es.unican.istr.rtgen.tool.mast.config;

/**
 * Created by JuanCTR on 01/09/2015.
 */
public enum MastToolConfigurableOptions {
    NAME, WORK_PATH, MAST_PATH, ANALYSIS_TOOL, ASSIGNMENT_TOOL, SYNC,
    HOSPA_INIT, HOSPA_Ka, HOSPA_Kr, HOSPA_ITERATIONS, HOSPA_OVERITERATIONS,
    ANALYSIS_STOP_FACTOR, LC_EDF_GSD, LC_EDF_DS_FACTOR, CALCULATE_SLACK, JITTER_AVOIDANCE
}
